name: Featured star list languages

on:
  # Planifiez des mises à jour quotidiennes
  schedule: [{cron: "0 0 * * *"}]
  # (optionnel) Exécutez le flux de travail manuellement
  workflow_dispatch:
  # (optionnel) Exécutez le flux de travail lors de la publication sur master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Featured star list languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.starlists.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 0
          plugin_starlists_only: Awesome
