name: Full-year calendar

on:
  # Planifiez des mises à jour quotidiennes
  schedule: [{cron: "0 0 * * *"}]
  # (optionnel) Exécutez le flux de travail manuellement
  workflow_dispatch:
  # (optionnel) Exécutez le flux de travail lors de la publication sur master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
