name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
      actions: read
      issues: read
      pull-requests: read
      repository-projects: read
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create dist directory
        run: mkdir -p dist

      - name: Collect GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Organization introduction
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.introduction.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Bubhux
          base: header
          plugin_introduction: yes

      - name: All achievements detailed display
        uses: stalomeow/metrics@projects-v2
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes

      - name: LeetCode
        uses: stalomeow/metrics@projects-v2
        with:
          filename: metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: "bubhux"
          plugin_leetcode_sections: solved, skills, recent

      - name: Python or JavaScript snippet of the day
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.code.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_code: yes
          plugin_code_languages: python, javascript
          plugin_code_load: 400

      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
            filename: metrics.plugin.languages.indepth.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_languages: yes
            plugin_languages_ignored: >-
                tex, less, makefile, qmake, lex, cmake, gnuplot
            plugin_languages_indepth: yes
            plugin_languages_details: lines, bytes-size, percentage
            plugin_languages_limit: 0

      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Repositories traffic
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.traffic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_traffic: yes

      - name: Using graph charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stargazers.graph.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts_type: graph

      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Europe/Paris

      - name: Featured star list
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.starlists.svg
          token: NOT_NEEDED
          base: ""
          plugin_starlists: yes
          plugin_starlists_limit_repositories: 2
          plugin_starlists_only: TC39

      - name: List files before commit
        run: ls -la

      - name: List files after metrics collection
        run: ls -la
